/* Generated By:JavaCC: Do not edit this line. maguConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface maguConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TK_FORWARD = 1;
  /** RegularExpression Id. */
  int TK_LEFT = 2;
  /** RegularExpression Id. */
  int TK_RIGHT = 3;
  /** RegularExpression Id. */
  int TK_PENCILUP = 4;
  /** RegularExpression Id. */
  int TK_PENCILDOWN = 5;
  /** RegularExpression Id. */
  int TK_MOVE = 6;
  /** RegularExpression Id. */
  int TK_SHOWPOS = 7;
  /** RegularExpression Id. */
  int TK_HIDEPOS = 8;
  /** RegularExpression Id. */
  int TK_HOME = 9;
  /** RegularExpression Id. */
  int TK_CURVE = 10;
  /** RegularExpression Id. */
  int TK_CLEAR = 11;
  /** RegularExpression Id. */
  int TK_INPUT = 12;
  /** RegularExpression Id. */
  int TK_PRINT = 13;
  /** RegularExpression Id. */
  int TK_WHILE = 14;
  /** RegularExpression Id. */
  int TK_IF = 15;
  /** RegularExpression Id. */
  int TK_ELSE = 16;
  /** RegularExpression Id. */
  int TK_ARR = 17;
  /** RegularExpression Id. */
  int TK_FUNC = 18;
  /** RegularExpression Id. */
  int TK_EQ = 19;
  /** RegularExpression Id. */
  int TK_NE = 20;
  /** RegularExpression Id. */
  int TK_LT = 21;
  /** RegularExpression Id. */
  int TK_GT = 22;
  /** RegularExpression Id. */
  int TK_LPAR = 23;
  /** RegularExpression Id. */
  int TK_RPAR = 24;
  /** RegularExpression Id. */
  int TK_LBRACKET = 25;
  /** RegularExpression Id. */
  int TK_RBRACKET = 26;
  /** RegularExpression Id. */
  int TK_COMMA = 27;
  /** RegularExpression Id. */
  int TK_PLUS = 28;
  /** RegularExpression Id. */
  int TK_MINUS = 29;
  /** RegularExpression Id. */
  int TK_MULT = 30;
  /** RegularExpression Id. */
  int TK_DIV = 31;
  /** RegularExpression Id. */
  int TK_CTE_I = 32;
  /** RegularExpression Id. */
  int TK_ID = 33;
  /** RegularExpression Id. */
  int TK_STRING = 34;
  /** RegularExpression Id. */
  int QUOTE = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<TK_FORWARD>",
    "<TK_LEFT>",
    "<TK_RIGHT>",
    "<TK_PENCILUP>",
    "<TK_PENCILDOWN>",
    "<TK_MOVE>",
    "<TK_SHOWPOS>",
    "<TK_HIDEPOS>",
    "<TK_HOME>",
    "<TK_CURVE>",
    "<TK_CLEAR>",
    "<TK_INPUT>",
    "<TK_PRINT>",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"arr\"",
    "\"func\"",
    "\"=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<TK_CTE_I>",
    "<TK_ID>",
    "<TK_STRING>",
    "\"\\\"\"",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
